http:
  enabled: false

input:
  redpanda_common:
    consumer_group: cg_d
    topics: [ '.*' ]
    regexp_topics: true
    auto_replay_nacks: false
    partition_buffer_bytes: 1KiB

  processors:
    - mutation: 'root.source_topic = @kafka_topic'

output:
  stdout: {}

redpanda:
  seed_brokers: [ localhost:9092 ]

metrics:
  prometheus:
    push_interval: 1s
    push_job_name: benthos_push
    push_url: "http://localhost:9091"

